spring:
    main:
      banner-mode: off

    artemis:
      mode: embedded  # server mode
      embedded:
        enabled: true
      host: localhost
      port: 61616
      keyStorePassword:
      keyStorePath:
      trustStorePath:
      trustStorePassword:
      enabledProtocols:
      enabledCipherSuites:
      needClientAuth: false
      sslEnabled: false
      batchDelay:
      connectionsAllowed:
      directDeliver: true
      tcpNoDelay: true
      tcpReceiveBufferSize: 32768
      tcpSendBufferSize: 32768
      verifyHost: false
      handshake-timeout: 30
      
server:
    port: 7779
    ssl:
        enabled: false
    error:
        include-exception: true
        include-message: always

management:
  endpoints:
    web:
      exposure:
        include: "*"